force-app/main/default/objects/Contact/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Doctors Medical Specialization</description>
    <label>Specialization</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Doctors</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Doctor_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Doctor_Record_Type</fullName>
    <active>true</active>
    <label>Doctor Record Type</label>
</RecordType>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <description>Medical clinic specializations</description>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Appointment_price__c.field-meta.xml
<CustomField>
    <fullName>Appointment_price__c</fullName>
    <description>Appointment price</description>
    <label>Appointment price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DoctorDataService.cls
/**
 * Created by Bogdan_Krasun on 21.12.2022.
 */

public with sharing class DoctorDataService {

    @AuraEnabled(Cacheable=true)
    public static List<Specialization__c> getSpecializations() {
        return [SELECT Name, Id, Appointment_price__c, Image_Url__c FROM Specialization__c WITH SECURITY_ENFORCED ORDER BY Name];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Contact> getDoctors(String specializationId) {
        String query = 'SELECT Id, Name, Image_Url__c FROM Contact WHERE RecordType.DeveloperName = \'Doctor_Record_Type\'';
        if (String.isNotBlank(specializationId)) {
            query += ' AND Specialization__c =:specializationId';
        }
        query += ' WITH SECURITY_ENFORCED ';
        System.debug('query contact - ' + query);
        return Database.query(query);
    }

}